### ISSUE TITLE
In latest build, 2.3 phone stop detecting headphones insert.

### ISSUE THREAD

**Issue by dorimanx** [reiryuki/Dolby-Atmos-Magic-Revision-Magisk-Module#1]
Hi,

in beta 2.3.1 no problem, when i plug headphones to oneplus 8t (usb connector) they are detected and apps play via module,
i can configure sound profiles.

in build 2.3 stable, headphones detected once, at boot, and then not, plug/unplug and phone uses only speaker, and no headphones icon.

Please fix.

Thank you!

**Comment by reiryuki** [comment]
Bug Report
https://t.me/androidryukimodsdiscussions/2618
If you don't do above, issues will be closed immediately

-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 4 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module X
3) Full logcat X
4) Zipped Z folder X

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.
