### ISSUE TITLE
Lost volume control

### ISSUE THREAD

**Issue by skenderbeggar** [reiryuki/Dolby-Atmos-Magic-Revision-Magisk-Module#2]
Hi,
installed on 1+90 Pro A12. works great except volume is at max and cannot control volume.

**Comment by reiryuki** [comment]
Bug Report
https://t.me/androidryukimodsdiscussions/2618
If you don't do above, issues will be closed immediately

-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 4 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module X
3) Full logcat X
4) Zipped Z folder X

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.

It will be re-opened after you have uploaded the 3 required files.
