### ISSUE TITLE
volume control loss and volume at full constantly

### ISSUE THREAD

**Issue by skenderbeggar** [reiryuki/Dolby-Atmos-Magic-Revision-Magisk-Module#3]
Loss of volume control and volume at full constantly. Logs attached. 

[magisk_install_log_2022-05-10T13_03_06.log](https://github.com/reiryuki/Dolby-Atmos-Magic-Revision-Magisk-Module/files/8663863/magisk_install_log_2022-05-10T13_03_06.log)
[logcat_05-10-2022_13-33-57.txt](https://github.com/reiryuki/Dolby-Atmos-Magic-Revision-Magisk-Module/files/8663864/logcat_05-10-2022_13-33-57.txt)
[z.zip](https://github.com/reiryuki/Dolby-Atmos-Magic-Revision-Magisk-Module/files/8663865/z.zip)

**Comment by reiryuki** [comment]
Try v2.4-beta.1 uploaded on pling
If the problem still occurs, send those 3 files again

**Comment by reiryuki** [comment]
Try edit /data/adb/modules(_update)/Atmos/service.sh

delete these lines:

![Screenshot_20220511-201258_MT Manager](https://user-images.githubusercontent.com/46316533/167858482-ba0a59fc-1163-4d6d-80f7-a1c7ed9e45fa.png)


reboot after

**Comment by skenderbeggar** [comment]
That did it!! And sent a donation as thanks!

**Comment by reiryuki** [comment]
Thanks so much bro, 🙏🙏🙏🙏
can you send your /my_product/etc/audio_policy_configuration.xml and /vendor/etc/audio_policy_configuration.xml ?

**Comment by skenderbeggar** [comment]
Here you go. 
[Audio_Policies.zip](https://github.com/reiryuki/Dolby-Atmos-Magic-Revision-Magisk-Module/files/8670587/Audio_Policies.zip)

**Comment by reiryuki** [comment]
Can you try with Hi-Res Magisk Module and AML Magisk Modules without deleting those lines above?

**Comment by skenderbeggar** [comment]
v2.4-beta.1 (with lines included) crashes with AML and Hi-Res(24bit) installed.
Previous installations of DolbyAtmos also crashed with AML installed.

**Comment by reiryuki** [comment]
ok
thia issue will be closed after the fixed version is released

**Comment by reiryuki** [comment]
Try v2.5-beta.1

**Comment by skenderbeggar** [comment]
Two thumbs up.
